--- 
title: "Probability, Risk, and Reward"
author: "Bill Bynum with Brian Avery"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/randombooks
description: "Probability and genetics, genetics and probability, free open-source book written in Rstudio with bookdown::gitbook."
---

# Preface {-}

## Motivation

Probability can be fun...and frustrating. Probability can clarify a complex situation...and sometimes be very counter-intuitive. Probability is often taught late in a formal mathematics education (if at all) with math tools including calculus and linear algebra but the results are important for many who may not have had access to these theoretical mathematical techniques such as social scientists, life scientists, business students, health science majors, and just plain-old citizens. Our experience teaching probability leads us to believe that there is a real need for teaching and explanatory materials in applied probability that is accessible without advanced prerequisite mathematics knowledge. 

To do this, we use a simple model of identifying an interesting problem and asking the learner to identify their preconceptions. When shared these preconceptions generate hypotheses and give the students a little skin in the game. Then the student is ready for some experience to compare against their preconceptions. We gain experience through data collection and simulation and this guides us to capture the theory that can explain the phenomena. Following this process of guided exploration we have seen students refine their intuition and develop probabilistically reasoning skills.  


## About the Author

Bill Bynum is an Associate Professor of mathematics at Westminster University with mathematical and statistical thinking at the entry level a key focus of my teaching. Bill has taught in the math and data science programs at Westminster since 1989. He has a M.A. in mathematics from University of Colorado.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
